version: "3.7"
services:
  columna:
    image: columna:local
    hostname: columna
    container_name: columna
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /tmp
      - ${LOCAL_DEV_COLUMNA_DIR-~/git/columna}:/app
    environment:
      - XDEBUG_CONFIG
      - PHP_IDE_CONFIG
      - ENVIRONMENT_NAME
    env_file:
      - .env
    restart: unless-stopped
    command:
      - sh
      - -ex
      - -c
      - |
        composer install --no-plugins --no-scripts --no-interaction
        tail -f /dev/null